[MC] Compute fragment offsets eagerly
This builds on top of commit 9d0754ada5dbbc0c009bcc2f7824488419cc5530
("[MC] Relax fragments eagerly") and relaxes fragments eagerly to
eliminate MCSection::HasLayout and `getFragmentOffset` overhead.

Note: The removed `#ifndef NDEBUG` code (disabled by default) in
X86AsmBackend::finishLayout was problematic, as (a) !NDEBUG and NDEBUG
builds evaluated fragment offsets at different times before this patch
(b) one iteration might not be sufficient to converge. There might be
some edge cases that it did not handle. Anyhow, this patch probably
makes it work for more cases.

---

1a47f3f3db66589c11f8ddacfeaecc03fb80c510 caused spurious

> error: value of -130 is too large for field of 1 byte

This exposed other preexisting problems:

* Size change of fill fragments does not influence the fixed-point iteration.
* The `invalid number of bytes` error is reported too early. Since
  `.zero A-B` might have temporary negative values in the first few
  iterations.

However, the problems did not seem to affect the Linux kernel builds.

`computeFragmentSize` at `layoutSection` time. This led to inconsistent
results in some edge cases when size expressions were label differences.
The layout algorithm change in 1a47f3f3db66589c11f8ddacfeaecc03fb80c510
exposed the issue, leading to #100283.

To fix this issue, perform relaxation and offset assignment in the same
loop.